#!/bin/bash

#script for monitoring power draw

status=$(cat /sys/class/power_supply/BAT0/status)

discharge=$(awk '{sum += $1} END {printf "%.2f W\n", sum/1000000}' /sys/class/power_supply/BAT0/power_now)

if [[ $status == "Charging" ]]; then
  echo "🔺$discharge"
else
  echo "🔻$discharge"
fi