#!/bin/bash

#alerts when battery is low %

BAT="/sys/class/power_supply/BAT0"

[ ! -d "$BAT" ] && exit 1

capacity=$(cat "$BAT/capacity")

status=$(cat "$BAT/status")

if [[ "$status" == "Charging" ]]; then
    exit 0
fi

if [ "$capacity" -le 30 ]; then
    notify-send -u critical -t 10000 "BATTERY LOW (${capacity}%)"
fi